---
  dataset: "ames"
  is_regression: True
  random_feat_split: True
  bound_dist: [15]
  is_bound_percent: True
  forward_batch_size: 4096
  # Ensemble parameters
  alt_type: "lgbm"
  n_disjoint_models: 51
  ssl_degree: 1
  # LightGBM params
  model_params:
    boosting_type: "gbdt"
    n_estimators: 500
    max_depth: 5
    num_leaves: 127
    objective: "mae"
    reg_alpha: 0.0
    reg_lambda: 0.0
    learning_rate: 0.3
    subsample: 0.5
    colsample_bytree: 0.5
    verbose: -1
